### ISSUE TITLE
Add plug-in mechanism(interface) for functions-framework

### ISSUE THREAD

**Issue by tpiperatgod** [OpenFunction/functions-framework#8]
## Feature request
We need to add an interface (similar to the lifecycle management standard) to the Functions-Framework. This interface will be used to provide standards for plug-in access and also to execute these plug-ins before the function is run.

## User case
This interface can be used by projects like [go2sky](https://github.com/SkyAPM/go2sky) to set anchor points in functions.

Refer issue [#146](https://github.com/OpenFunction/OpenFunction/issues/146)

**Comment by ForeverArt** [comment]
For the end span in skywalking, post-run is needed as well. Maybe the onion architecture is a great choice for further plugins/middlewares.

Besides, most Functions need same plugins to make things right. Maybe a control plane is needed for openfunction-controller? So that we would have global plugins and function plugins.

Really interested in what plugin architecture OpenFunction would use and what changes it would bring to building and serving stages.

**Comment by tpiperatgod** [comment]
@ForeverArt Thank you for the suggestion! I will refer to the Onion Architecture.

I'm considering some detailed proposals that include a plugin mechanism for implementing OpenFunction in the form of a [lifecycle](https://buildpacks.io/docs/concepts/components/lifecycle/) of buildpacks.

And I hope to be able to abstract more generic parts of it so that it can be implemented in the same language, which would reduce the cost of dealing with functions-framework in different languages.

Feel free to join the #9. We can discuss the implementation proposals for the plugin mechanism here.

**Comment by benjaminhuo** [comment]
Proposal for plugin mechanism to function framework by @tpiperatgod https://hackmd.io/XwHWmAJwQWeCu18zQ97s_A?view=

**Comment by benjaminhuo** [comment]
Proposal created for this: https://github.com/OpenFunction/OpenFunction/blob/main/docs/proposals/202112_functions_framework_refactoring.md

**Comment by benjaminhuo** [comment]
close this via https://github.com/OpenFunction/functions-framework-go/pull/22
